NO-TICKET - Fix Build Failures
- The 3.14.4 aarch64 asc file is missing-so I've reverted to 3.14.3
until that is sorted out
- Added better error handling with issues for the ASC download failure
- Fixed up the cleanup process so it should hopefully work better on
both local and GHA
Signed-off-by: Troy Fontaine <tfontaine@troyfontaine.com>

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -2,7 +2,7 @@
 version: '3'
 
 env:
-  RELEASES: ( "3.9.6" "3.10.9" "3.11.13" "3.12.10" "3.13.8" "3.14.4" "3.15.2")
+  RELEASES: ( "3.9.6" "3.10.9" "3.11.13" "3.12.10" "3.13.8" "3.14.3" "3.15.2")
   ARCHITECTURES: ( "x86_64" "aarch64" "armhf" )
   OWNER: "troyfontaine"
   REPOSITORY: "alpinelinux"
@@ -18,7 +18,6 @@ tasks:
       - task: build-local
       - task: test-images
       - task: cleanup
-      - task: remove-buildx-builder
 
   build-test-gha:
     desc: Build images to test via GHA
@@ -52,12 +51,6 @@ tasks:
         docker buildx create --name alpinebuilder \
         --platform linux/arm64,linux/amd64,linux/armhf \
         --driver docker-container --use
-
-  remove-buildx-builder:
-    desc: Setup
-    cmds:
-      - |
-        docker buildx rm alpinebuilder
 
   get-signingkey:
     desc: Get the Alpine signing key
@@ -95,14 +88,18 @@ tasks:
             URI_PATH="alpine-minirootfs-${release}-${arch}.tar.gz"
 
             # Grab our root file system
-            wget -q -O \
+            if ! wget -q -O \
               "./filesystem/${version}/$target_arch/alpine.tar.gz" \
-              "{{ .CDN }}/v${version}/releases/${arch}/${URI_PATH}"
+              "{{ .CDN }}/v${version}/releases/${arch}/${URI_PATH}"; then
+                echo "Failed to download version ${version} for arch ${arch}"
+            fi
 
             # Grab the signature for the file
-            wget -q -O \
+            if ! wget -q -O \
               "./filesystem/${version}/$target_arch/key.asc" \
-              "{{ .CDN }}/v${version}/releases/${arch}/${URI_PATH}.asc"
+              "{{ .CDN }}/v${version}/releases/${arch}/${URI_PATH}.asc"; then
+              echo "Failed to download signature file version ${version} for arch ${arch}"
+            fi
 
             # Validate the downloaded root file system
             if ! gpg --verify "./filesystem/${version}/$target_arch/key.asc"\
@@ -365,3 +362,4 @@ tasks:
           version=$(echo "$release" | cut -f1,2 -d'.' )
           rm -rf "./filesystem/$version"
         done
+        docker buildx rm alpinebuilder || true
